export enum InventorySearch {
  CALENDAR = 'CALENDAR',
  FILEORDERSOURCE = 'FILEORDERSOURCE',
  JOBRESOURCE = 'JOBRESOURCE',
  JOBTEMPLATE = 'JOBTEMPLATE',
  NOTICEBOARD = 'NOTICEBOARD',
  LOCK = 'LOCK',
  SCHEDULE = 'SCHEDULE',
  INCLUDESCRIPT = 'INCLUDESCRIPT',
  WORKFLOW = 'WORKFLOW',
}

export enum InventoryForHistory {
  WORKFLOW = 'WORKFLOW',
  FILEORDERSOURCE = 'FILEORDERSOURCE',
  JOBRESOURCE = 'JOBRESOURCE',
  NOTICEBOARD = 'NOTICEBOARD',
  LOCK = 'LOCK',
}

export enum InventoryObject {
  WORKFLOW = 'WORKFLOW',
  FILEORDERSOURCE = 'FILEORDERSOURCE',
  JOBTEMPLATE = 'JOBTEMPLATE',
  JOBRESOURCE = 'JOBRESOURCE',
  NOTICEBOARD = 'NOTICEBOARD',
  LOCK = 'LOCK',
  INCLUDESCRIPT = 'INCLUDESCRIPT',
  SCHEDULE = 'SCHEDULE',
  WORKINGDAYSCALENDAR = 'WORKINGDAYSCALENDAR',
  NONWORKINGDAYSCALENDAR = 'NONWORKINGDAYSCALENDAR'
}
