export enum InventorySearch {
  WORKFLOW= 'WORKFLOW',
  FILEORDERSOURCE = 'FILEORDERSOURCE',
  JOBRESOURCE = 'JOBRESOURCE',
  NOTICEBOARD = 'NOTICEBOARD',
  LOCK = 'LOCK',
  SCHEDULE = 'SCHEDULE',
  CALENDAR = 'CALENDAR'
}

export enum InventoryForHistory {
  WORKFLOW= 'WORKFLOW',
  FILEORDERSOURCE = 'FILEORDERSOURCE',
  JOBRESOURCE = 'JOBRESOURCE',
  NOTICEBOARD = 'NOTICEBOARD',
  LOCK = 'LOCK',
}

export enum InventoryObject {
  WORKFLOW= 'WORKFLOW',
  FILEORDERSOURCE = 'FILEORDERSOURCE',
  JOBRESOURCE = 'JOBRESOURCE',
  NOTICEBOARD = 'NOTICEBOARD',
  LOCK = 'LOCK',
  SCHEDULE = 'SCHEDULE',
  WORKINGDAYSCALENDAR = 'WORKINGDAYSCALENDAR',
  NONWORKINGDAYSCALENDAR = 'NONWORKINGDAYSCALENDAR'
}
